/* Do not modify this file, it was automatically generated by CMake. */

/*
 * Define the KiCad build version strings.
 */
#ifndef __KICAD_VERSION_H__
#define __KICAD_VERSION_H__

#ifndef INCLUDE_KICAD_VERSION
#error Do not include kicad_build_version.h directly.  Include build_version.h instead.
#endif

#define KICAD_COMMIT_HASH               "06e74c95158dd4b8596027633b2b2a4dba738395"
#define KICAD_VERSION                   "9.99.0-751-g06e74c9515"
#define KICAD_VERSION_FULL              "9.99.0-751-g06e74c9515"
#define KICAD_SEMANTIC_VERSION          "9.99.0-unknown"
#define KICAD_MAJOR_VERSION             "9"
#define KICAD_MINOR_VERSION             "99"
#define KICAD_PATCH_VERSION             "0"
#define KICAD_IS_NIGHTLY                1
#define KICAD_MAJOR_MINOR_VERSION       "9.99"
#define KICAD_MAJOR_MINOR_PATCH_VERSION "9.99.0"
#define KICAD_MAJOR_MINOR_PATCH_TUPLE   { 9, 99, 0 }
#define KICAD_WIN32_RC_PRODVER          9, 99, 0, 42355
#define KICAD_WIN32_RC_PRODVER_STR      "9.99.0\0"
#define KICAD_WIN32_RC_FILEVER          9, 99, 0, 42355
#define KICAD_WIN32_RC_FILEVER_STR      "9.99.0.42355\0"

#endif  /* __KICAD_VERSION_H__ */
