/* Do not modify this file, it was automatically generated by CMake. */

/*
 * Define the KiCad build version string.
 */
#ifndef __KICAD_VERSION_H__
#define __KICAD_VERSION_H__

#define KICAD_VERSION_FULL "(5.1.12-9-gc9c6ea6729-dirty)-beautiful"

#endif  /* __KICAD_VERSION_H__ */
