// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schematic/schematic_commands.proto

#include "schematic/schematic_commands.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace kiapi {
namespace schematic {
namespace types {
}  // namespace types
}  // namespace schematic
}  // namespace kiapi
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_schematic_2fschematic_5fcommands_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_schematic_2fschematic_5fcommands_2eproto = nullptr;
const uint32_t TableStruct_schematic_2fschematic_5fcommands_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_schematic_2fschematic_5fcommands_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\"schematic/schematic_commands.proto\022\025ki"
  "api.schematic.typesb\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_schematic_2fschematic_5fcommands_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_schematic_2fschematic_5fcommands_2eproto = {
  false, false, 67, descriptor_table_protodef_schematic_2fschematic_5fcommands_2eproto, "schematic/schematic_commands.proto", 
  &descriptor_table_schematic_2fschematic_5fcommands_2eproto_once, nullptr, 0, 0,
  schemas, file_default_instances, TableStruct_schematic_2fschematic_5fcommands_2eproto::offsets,
  nullptr, file_level_enum_descriptors_schematic_2fschematic_5fcommands_2eproto, file_level_service_descriptors_schematic_2fschematic_5fcommands_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_schematic_2fschematic_5fcommands_2eproto_getter() {
  return &descriptor_table_schematic_2fschematic_5fcommands_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_schematic_2fschematic_5fcommands_2eproto(&descriptor_table_schematic_2fschematic_5fcommands_2eproto);
namespace kiapi {
namespace schematic {
namespace types {

// @@protoc_insertion_point(namespace_scope)
}  // namespace types
}  // namespace schematic
}  // namespace kiapi
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
