
/* Do not modify this file it was automatically generated by the
 * TokenList2DsnLexer CMake script.
 *
 * Include this file in your lexer class to provide the keywords for
 * your DSN lexer.
 */

#include </opt/kicad/program/master/Tears_Master/build/common/drc_rules_lexer.h>

using namespace DRCRULE_T;

#define TOKDEF(x)    { #x, T_##x }

const KEYWORD DRC_RULES_LEXER::keywords[] = {
    TOKDEF( annular_width ),
    TOKDEF( assertion ),
    TOKDEF( board_edge ),
    TOKDEF( buried_via ),
    TOKDEF( clearance ),
    TOKDEF( condition ),
    TOKDEF( connection_width ),
    TOKDEF( constraint ),
    TOKDEF( courtyard_clearance ),
    TOKDEF( creepage ),
    TOKDEF( diff_pair_gap ),
    TOKDEF( diff_pair_uncoupled ),
    TOKDEF( disallow ),
    TOKDEF( edge_clearance ),
    TOKDEF( error ),
    TOKDEF( exclusion ),
    TOKDEF( footprint ),
    TOKDEF( graphic ),
    TOKDEF( hole ),
    TOKDEF( hole_clearance ),
    TOKDEF( hole_size ),
    TOKDEF( hole_to_hole ),
    TOKDEF( ignore ),
    TOKDEF( inner ),
    TOKDEF( layer ),
    TOKDEF( length ),
    TOKDEF( max ),
    TOKDEF( mechanical_clearance ),
    TOKDEF( mechanical_hole_clearance ),
    TOKDEF( micro_via ),
    TOKDEF( min ),
    TOKDEF( min_resolved_spokes ),
    TOKDEF( none ),
    TOKDEF( npth ),
    TOKDEF( opt ),
    TOKDEF( outer ),
    TOKDEF( pad ),
    TOKDEF( physical_clearance ),
    TOKDEF( physical_hole_clearance ),
    TOKDEF( pth ),
    TOKDEF( rule ),
    TOKDEF( severity ),
    TOKDEF( silk_clearance ),
    TOKDEF( skew ),
    TOKDEF( solid ),
    TOKDEF( text ),
    TOKDEF( text_height ),
    TOKDEF( text_thickness ),
    TOKDEF( thermal_relief_gap ),
    TOKDEF( thermal_reliefs ),
    TOKDEF( thermal_spoke_width ),
    TOKDEF( track ),
    TOKDEF( track_angle ),
    TOKDEF( track_segment_length ),
    TOKDEF( track_width ),
    TOKDEF( version ),
    TOKDEF( via ),
    TOKDEF( via_count ),
    TOKDEF( via_diameter ),
    TOKDEF( warning ),
    TOKDEF( within_diff_pairs ),
    TOKDEF( zone ),
    TOKDEF( zone_connection )
};

const unsigned DRC_RULES_LEXER::keyword_count = unsigned( sizeof( DRC_RULES_LEXER::keywords )/sizeof( DRC_RULES_LEXER::keywords[0] ) );


const char* DRC_RULES_LEXER::TokenName( T aTok )
{
    const char* ret;

    if( aTok < 0 )
        ret = DSNLEXER::Syntax( aTok );
    else if( (unsigned) aTok < keyword_count )
        ret = keywords[aTok].name;
    else
        ret = "token too big";

    return ret;
}


const KEYWORD_MAP DRC_RULES_LEXER::keywords_hash({
    { "annular_width", 0 },
    { "assertion", 1 },
    { "board_edge", 2 },
    { "buried_via", 3 },
    { "clearance", 4 },
    { "condition", 5 },
    { "connection_width", 6 },
    { "constraint", 7 },
    { "courtyard_clearance", 8 },
    { "creepage", 9 },
    { "diff_pair_gap", 10 },
    { "diff_pair_uncoupled", 11 },
    { "disallow", 12 },
    { "edge_clearance", 13 },
    { "error", 14 },
    { "exclusion", 15 },
    { "footprint", 16 },
    { "graphic", 17 },
    { "hole", 18 },
    { "hole_clearance", 19 },
    { "hole_size", 20 },
    { "hole_to_hole", 21 },
    { "ignore", 22 },
    { "inner", 23 },
    { "layer", 24 },
    { "length", 25 },
    { "max", 26 },
    { "mechanical_clearance", 27 },
    { "mechanical_hole_clearance", 28 },
    { "micro_via", 29 },
    { "min", 30 },
    { "min_resolved_spokes", 31 },
    { "none", 32 },
    { "npth", 33 },
    { "opt", 34 },
    { "outer", 35 },
    { "pad", 36 },
    { "physical_clearance", 37 },
    { "physical_hole_clearance", 38 },
    { "pth", 39 },
    { "rule", 40 },
    { "severity", 41 },
    { "silk_clearance", 42 },
    { "skew", 43 },
    { "solid", 44 },
    { "text", 45 },
    { "text_height", 46 },
    { "text_thickness", 47 },
    { "thermal_relief_gap", 48 },
    { "thermal_reliefs", 49 },
    { "thermal_spoke_width", 50 },
    { "track", 51 },
    { "track_angle", 52 },
    { "track_segment_length", 53 },
    { "track_width", 54 },
    { "version", 55 },
    { "via", 56 },
    { "via_count", 57 },
    { "via_diameter", 58 },
    { "warning", 59 },
    { "within_diff_pairs", 60 },
    { "zone", 61 },
    { "zone_connection", 62 }
});