
/* Do not modify this file it was automatically generated by the
 * TokenList2DsnLexer CMake script.
 *
 * Include this file in your lexer class to provide the keywords for
 * your DSN lexer.
 */

#include </opt/kicad/program/master/Tears_Master/build/common/embedded_files_lexer.h>

using namespace EMBEDDED_FILES_T;

#define TOKDEF(x)    { #x, T_##x }

const KEYWORD EMBEDDED_FILES_LEXER::keywords[] = {
    TOKDEF( checksum ),
    TOKDEF( data ),
    TOKDEF( datasheet ),
    TOKDEF( embedded_files ),
    TOKDEF( embedded_fonts ),
    TOKDEF( file ),
    TOKDEF( font ),
    TOKDEF( model ),
    TOKDEF( name ),
    TOKDEF( other ),
    TOKDEF( reference ),
    TOKDEF( type ),
    TOKDEF( worksheet )
};

const unsigned EMBEDDED_FILES_LEXER::keyword_count = unsigned( sizeof( EMBEDDED_FILES_LEXER::keywords )/sizeof( EMBEDDED_FILES_LEXER::keywords[0] ) );


const char* EMBEDDED_FILES_LEXER::TokenName( T aTok )
{
    const char* ret;

    if( aTok < 0 )
        ret = DSNLEXER::Syntax( aTok );
    else if( (unsigned) aTok < keyword_count )
        ret = keywords[aTok].name;
    else
        ret = "token too big";

    return ret;
}


const KEYWORD_MAP EMBEDDED_FILES_LEXER::keywords_hash({
    { "checksum", 0 },
    { "data", 1 },
    { "datasheet", 2 },
    { "embedded_files", 3 },
    { "embedded_fonts", 4 },
    { "file", 5 },
    { "font", 6 },
    { "model", 7 },
    { "name", 8 },
    { "other", 9 },
    { "reference", 10 },
    { "type", 11 },
    { "worksheet", 12 }
});