
/* Do not modify this file it was automatically generated by the
 * TokenList2DsnLexer CMake script.
 *
 * Include this file in your lexer class to provide the keywords for
 * your DSN lexer.
 */

#include </opt/kicad/program/master/Tears_Master/build/common/stroke_params_lexer.h>

using namespace STROKEPARAMS_T;

#define TOKDEF(x)    { #x, T_##x }

const KEYWORD STROKE_PARAMS_LEXER::keywords[] = {
    TOKDEF( color ),
    TOKDEF( dash ),
    TOKDEF( dash_dot ),
    TOKDEF( dash_dot_dot ),
    TOKDEF( default ),
    TOKDEF( dot ),
    TOKDEF( solid ),
    TOKDEF( stroke ),
    TOKDEF( type ),
    TOKDEF( width )
};

const unsigned STROKE_PARAMS_LEXER::keyword_count = unsigned( sizeof( STROKE_PARAMS_LEXER::keywords )/sizeof( STROKE_PARAMS_LEXER::keywords[0] ) );


const char* STROKE_PARAMS_LEXER::TokenName( T aTok )
{
    const char* ret;

    if( aTok < 0 )
        ret = DSNLEXER::Syntax( aTok );
    else if( (unsigned) aTok < keyword_count )
        ret = keywords[aTok].name;
    else
        ret = "token too big";

    return ret;
}


const KEYWORD_MAP STROKE_PARAMS_LEXER::keywords_hash({
    { "color", 0 },
    { "dash", 1 },
    { "dash_dot", 2 },
    { "dash_dot_dot", 3 },
    { "default", 4 },
    { "dot", 5 },
    { "solid", 6 },
    { "stroke", 7 },
    { "type", 8 },
    { "width", 9 }
});