
/* Do not modify this file it was automatically generated by the
 * TokenList2DsnLexer CMake script.
 *
 * Include this file in your lexer class to provide the keywords for
 * your DSN lexer.
 */

#include </opt/kicad/program/master/Tears_Master/build/common/drawing_sheet/drawing_sheet_lexer.h>

using namespace DRAWINGSHEET_T;

#define TOKDEF(x)    { #x, T_##x }

const KEYWORD DRAWING_SHEET_LEXER::keywords[] = {
    TOKDEF( bitmap ),
    TOKDEF( bold ),
    TOKDEF( bottom ),
    TOKDEF( bottom_margin ),
    TOKDEF( center ),
    TOKDEF( color ),
    TOKDEF( comment ),
    TOKDEF( data ),
    TOKDEF( drawing_sheet ),
    TOKDEF( end ),
    TOKDEF( face ),
    TOKDEF( font ),
    TOKDEF( generator ),
    TOKDEF( generator_version ),
    TOKDEF( incrlabel ),
    TOKDEF( incrx ),
    TOKDEF( incry ),
    TOKDEF( italic ),
    TOKDEF( justify ),
    TOKDEF( kicad_wks ),
    TOKDEF( lbcorner ),
    TOKDEF( left ),
    TOKDEF( left_margin ),
    TOKDEF( line ),
    TOKDEF( linewidth ),
    TOKDEF( ltcorner ),
    TOKDEF( maxheight ),
    TOKDEF( maxlen ),
    TOKDEF( name ),
    TOKDEF( notonpage1 ),
    TOKDEF( option ),
    TOKDEF( page1only ),
    TOKDEF( page_layout ),
    TOKDEF( pngdata ),
    TOKDEF( polygon ),
    TOKDEF( pos ),
    TOKDEF( pts ),
    TOKDEF( rbcorner ),
    TOKDEF( rect ),
    TOKDEF( repeat ),
    TOKDEF( right ),
    TOKDEF( right_margin ),
    TOKDEF( rotate ),
    TOKDEF( rtcorner ),
    TOKDEF( scale ),
    TOKDEF( setup ),
    TOKDEF( size ),
    TOKDEF( start ),
    TOKDEF( tbtext ),
    TOKDEF( textlinewidth ),
    TOKDEF( textsize ),
    TOKDEF( top ),
    TOKDEF( top_margin ),
    TOKDEF( version ),
    TOKDEF( xy )
};

const unsigned DRAWING_SHEET_LEXER::keyword_count = unsigned( sizeof( DRAWING_SHEET_LEXER::keywords )/sizeof( DRAWING_SHEET_LEXER::keywords[0] ) );


const char* DRAWING_SHEET_LEXER::TokenName( T aTok )
{
    const char* ret;

    if( aTok < 0 )
        ret = DSNLEXER::Syntax( aTok );
    else if( (unsigned) aTok < keyword_count )
        ret = keywords[aTok].name;
    else
        ret = "token too big";

    return ret;
}


const KEYWORD_MAP DRAWING_SHEET_LEXER::keywords_hash({
    { "bitmap", 0 },
    { "bold", 1 },
    { "bottom", 2 },
    { "bottom_margin", 3 },
    { "center", 4 },
    { "color", 5 },
    { "comment", 6 },
    { "data", 7 },
    { "drawing_sheet", 8 },
    { "end", 9 },
    { "face", 10 },
    { "font", 11 },
    { "generator", 12 },
    { "generator_version", 13 },
    { "incrlabel", 14 },
    { "incrx", 15 },
    { "incry", 16 },
    { "italic", 17 },
    { "justify", 18 },
    { "kicad_wks", 19 },
    { "lbcorner", 20 },
    { "left", 21 },
    { "left_margin", 22 },
    { "line", 23 },
    { "linewidth", 24 },
    { "ltcorner", 25 },
    { "maxheight", 26 },
    { "maxlen", 27 },
    { "name", 28 },
    { "notonpage1", 29 },
    { "option", 30 },
    { "page1only", 31 },
    { "page_layout", 32 },
    { "pngdata", 33 },
    { "polygon", 34 },
    { "pos", 35 },
    { "pts", 36 },
    { "rbcorner", 37 },
    { "rect", 38 },
    { "repeat", 39 },
    { "right", 40 },
    { "right_margin", 41 },
    { "rotate", 42 },
    { "rtcorner", 43 },
    { "scale", 44 },
    { "setup", 45 },
    { "size", 46 },
    { "start", 47 },
    { "tbtext", 48 },
    { "textlinewidth", 49 },
    { "textsize", 50 },
    { "top", 51 },
    { "top_margin", 52 },
    { "version", 53 },
    { "xy", 54 }
});