
/* Do not modify this file it was automatically generated by the
 * TokenList2DsnLexer CMake script.
 *
 * Include this file in your lexer class to provide the keywords for
 * your DSN lexer.
 */

#include </opt/kicad/program/master/Tears_Master/build/eeschema/dialogs/dialog_bom_cfg_lexer.h>

using namespace T_BOMCFG_T;

#define TOKDEF(x)    { #x, T_##x }

const KEYWORD DIALOG_BOM_CFG_LEXER::keywords[] = {
    TOKDEF( cmd ),
    TOKDEF( opts ),
    TOKDEF( plugin ),
    TOKDEF( plugins )
};

const unsigned DIALOG_BOM_CFG_LEXER::keyword_count = unsigned( sizeof( DIALOG_BOM_CFG_LEXER::keywords )/sizeof( DIALOG_BOM_CFG_LEXER::keywords[0] ) );


const char* DIALOG_BOM_CFG_LEXER::TokenName( T aTok )
{
    const char* ret;

    if( aTok < 0 )
        ret = DSNLEXER::Syntax( aTok );
    else if( (unsigned) aTok < keyword_count )
        ret = keywords[aTok].name;
    else
        ret = "token too big";

    return ret;
}


const KEYWORD_MAP DIALOG_BOM_CFG_LEXER::keywords_hash({
    { "cmd", 0 },
    { "opts", 1 },
    { "plugin", 2 },
    { "plugins", 3 }
});